ibex --abodybuilder3\
	--fv-heavy EIQLQQTGPELVQPGASVKISCKASGYSFTDYIMVWVKQSHGKGLEWIGNINPYHGRTAYNLKFKGKATLTVDKSSSTAFMQLNSLISEDSAVFYCVRKGYVEGGGLDYWGQGTSVIVS\
	--fv-light DIVLTQFPGSLAVSLGQRATISCKASQRVDYDGVSYMNWYQQKPGQPPKLLINAASDLESGIPARFSGTGSGTDFTLNIHPVEEEDAATYYCQQSNYDPWTFGGGTKLEIKRA\
	#--ckpt /weights/ibex/abb3.ckpt\
	#--output /workdir/antibody.pdb
