ibex --abodybuilder3\
	--fv-heavy MATGQVKLQQSGAEFVKAGASVKLSCKTSGYTFNNYWIHWVKQSPGQGLEWIGEIDPSDGYSNYNQKFKGKATLTVDKSSSTAYMHLNSLTSEDSAVYYCTSSTSVGGSWGQGTTVTVS\
	--fv-light MSDIELTQSPLSLPVSLGDQASISCTSSQSLLHSNGDTYLHWYLQKPGQSPKLLIYTLSNRFSGVPDRFSGSGSGTDFTLKISRVEAADLGIYFCSQTTHVPYTFGGGTK\
	#--ckpt /weights/ibex/abb3.ckpt\
	#--output /workdir/antibody.pdb
